// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Plain-data view of a task, for handing across the FFI boundary to Dart.
class TaskRecord {
  final String id;
  final String projectId;
  final String title;
  final String notes;
  final PlatformInt64? dueMillis;
  final List<String> tags;
  final String status;
  final PlatformInt64 priority;
  final PlatformInt64 createdAtMillis;
  final PlatformInt64 updatedAtMillis;

  const TaskRecord({
    required this.id,
    required this.projectId,
    required this.title,
    required this.notes,
    this.dueMillis,
    required this.tags,
    required this.status,
    required this.priority,
    required this.createdAtMillis,
    required this.updatedAtMillis,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      projectId.hashCode ^
      title.hashCode ^
      notes.hashCode ^
      dueMillis.hashCode ^
      tags.hashCode ^
      status.hashCode ^
      priority.hashCode ^
      createdAtMillis.hashCode ^
      updatedAtMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskRecord &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          projectId == other.projectId &&
          title == other.title &&
          notes == other.notes &&
          dueMillis == other.dueMillis &&
          tags == other.tags &&
          status == other.status &&
          priority == other.priority &&
          createdAtMillis == other.createdAtMillis &&
          updatedAtMillis == other.updatedAtMillis;
}
