// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'crdt.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -2130557055;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'cycles_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<TaskRecord>> crateApiAllTasks();

  Future<void> crateApiApplyTaskEdit({required TaskRecord task});

  Future<Uint8List?> crateApiGenerateSyncMessage({required String peerId});

  Future<String> crateApiGetDeviceId();

  Future<List<BlePeerIdentity>> crateApiGetTrustedPeers();

  Future<void> crateApiInitCrdt({required String dbPath});

  Future<bool> crateApiIsBleAdvertising();

  Future<List<TaskRecord>> crateApiMergeIncoming({
    required String peerId,
    required List<int> bytes,
  });

  Future<String> crateApiPing({required String name});

  Future<Uint8List?> crateApiProcessCrdtSyncPayload({
    required String peerId,
    required List<int> bytes,
  });

  Future<List<BlePeer>> crateApiScanBlePeers();

  Future<List<LanPeerInfo>> crateApiScanLanPeers();

  Future<void> crateApiSetPeerTrust({
    required String peerId,
    required bool trusted,
  });

  Future<String> crateApiStartBleAdvertising();

  Future<void> crateApiStartLanAdvertising();

  Future<void> crateApiStopBleAdvertising();

  Future<BleSyncReport> crateApiSyncWithPeerBle({
    required String peerId,
    required String address,
  });

  Future<LanSyncReport> crateApiSyncWithPeerLan({
    required String peerId,
    required String address,
  });

  Future<RelaySyncReport> crateApiSyncWithPeerRelay({
    required String peerId,
    required String relayUrl,
    required String token,
  });

  Future<WifiDirectSyncReport> crateApiSyncWithPeerWifiDirect({
    required String peerId,
    required String address,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<TaskRecord>> crateApiAllTasks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_task_record,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAllTasksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAllTasksConstMeta =>
      const TaskConstMeta(debugName: "all_tasks", argNames: []);

  @override
  Future<void> crateApiApplyTaskEdit({required TaskRecord task}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_task_record(task, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiApplyTaskEditConstMeta,
        argValues: [task],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiApplyTaskEditConstMeta =>
      const TaskConstMeta(debugName: "apply_task_edit", argNames: ["task"]);

  @override
  Future<Uint8List?> crateApiGenerateSyncMessage({required String peerId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGenerateSyncMessageConstMeta,
        argValues: [peerId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateSyncMessageConstMeta =>
      const TaskConstMeta(
        debugName: "generate_sync_message",
        argNames: ["peerId"],
      );

  @override
  Future<String> crateApiGetDeviceId() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetDeviceIdConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetDeviceIdConstMeta =>
      const TaskConstMeta(debugName: "get_device_id", argNames: []);

  @override
  Future<List<BlePeerIdentity>> crateApiGetTrustedPeers() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ble_peer_identity,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetTrustedPeersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetTrustedPeersConstMeta =>
      const TaskConstMeta(debugName: "get_trusted_peers", argNames: []);

  @override
  Future<void> crateApiInitCrdt({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiInitCrdtConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitCrdtConstMeta =>
      const TaskConstMeta(debugName: "init_crdt", argNames: ["dbPath"]);

  @override
  Future<bool> crateApiIsBleAdvertising() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIsBleAdvertisingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIsBleAdvertisingConstMeta =>
      const TaskConstMeta(debugName: "is_ble_advertising", argNames: []);

  @override
  Future<List<TaskRecord>> crateApiMergeIncoming({
    required String peerId,
    required List<int> bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_task_record,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiMergeIncomingConstMeta,
        argValues: [peerId, bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMergeIncomingConstMeta => const TaskConstMeta(
    debugName: "merge_incoming",
    argNames: ["peerId", "bytes"],
  );

  @override
  Future<String> crateApiPing({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPingConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPingConstMeta =>
      const TaskConstMeta(debugName: "ping", argNames: ["name"]);

  @override
  Future<Uint8List?> crateApiProcessCrdtSyncPayload({
    required String peerId,
    required List<int> bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProcessCrdtSyncPayloadConstMeta,
        argValues: [peerId, bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProcessCrdtSyncPayloadConstMeta =>
      const TaskConstMeta(
        debugName: "process_crdt_sync_payload",
        argNames: ["peerId", "bytes"],
      );

  @override
  Future<List<BlePeer>> crateApiScanBlePeers() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_ble_peer,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiScanBlePeersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanBlePeersConstMeta =>
      const TaskConstMeta(debugName: "scan_ble_peers", argNames: []);

  @override
  Future<List<LanPeerInfo>> crateApiScanLanPeers() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_lan_peer_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiScanLanPeersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanLanPeersConstMeta =>
      const TaskConstMeta(debugName: "scan_lan_peers", argNames: []);

  @override
  Future<void> crateApiSetPeerTrust({
    required String peerId,
    required bool trusted,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_bool(trusted, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSetPeerTrustConstMeta,
        argValues: [peerId, trusted],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetPeerTrustConstMeta => const TaskConstMeta(
    debugName: "set_peer_trust",
    argNames: ["peerId", "trusted"],
  );

  @override
  Future<String> crateApiStartBleAdvertising() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStartBleAdvertisingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStartBleAdvertisingConstMeta =>
      const TaskConstMeta(debugName: "start_ble_advertising", argNames: []);

  @override
  Future<void> crateApiStartLanAdvertising() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStartLanAdvertisingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStartLanAdvertisingConstMeta =>
      const TaskConstMeta(debugName: "start_lan_advertising", argNames: []);

  @override
  Future<void> crateApiStopBleAdvertising() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStopBleAdvertisingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStopBleAdvertisingConstMeta =>
      const TaskConstMeta(debugName: "stop_ble_advertising", argNames: []);

  @override
  Future<BleSyncReport> crateApiSyncWithPeerBle({
    required String peerId,
    required String address,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_String(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_ble_sync_report,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWithPeerBleConstMeta,
        argValues: [peerId, address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWithPeerBleConstMeta => const TaskConstMeta(
    debugName: "sync_with_peer_ble",
    argNames: ["peerId", "address"],
  );

  @override
  Future<LanSyncReport> crateApiSyncWithPeerLan({
    required String peerId,
    required String address,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_String(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_lan_sync_report,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWithPeerLanConstMeta,
        argValues: [peerId, address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWithPeerLanConstMeta => const TaskConstMeta(
    debugName: "sync_with_peer_lan",
    argNames: ["peerId", "address"],
  );

  @override
  Future<RelaySyncReport> crateApiSyncWithPeerRelay({
    required String peerId,
    required String relayUrl,
    required String token,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_String(relayUrl, serializer);
          sse_encode_String(token, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_relay_sync_report,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWithPeerRelayConstMeta,
        argValues: [peerId, relayUrl, token],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWithPeerRelayConstMeta => const TaskConstMeta(
    debugName: "sync_with_peer_relay",
    argNames: ["peerId", "relayUrl", "token"],
  );

  @override
  Future<WifiDirectSyncReport> crateApiSyncWithPeerWifiDirect({
    required String peerId,
    required String address,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(peerId, serializer);
          sse_encode_String(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wifi_direct_sync_report,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncWithPeerWifiDirectConstMeta,
        argValues: [peerId, address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncWithPeerWifiDirectConstMeta =>
      const TaskConstMeta(
        debugName: "sync_with_peer_wifi_direct",
        argNames: ["peerId", "address"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BlePeer dco_decode_ble_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BlePeer(
      deviceId: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      address: dco_decode_String(arr[2]),
      rssi: dco_decode_opt_box_autoadd_i_16(arr[3]),
    );
  }

  @protected
  BlePeerIdentity dco_decode_ble_peer_identity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BlePeerIdentity(
      deviceId: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      trusted: dco_decode_bool(arr[2]),
      lastSyncedAt: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  BleSyncReport dco_decode_ble_sync_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BleSyncReport(
      peerId: dco_decode_String(arr[0]),
      success: dco_decode_bool(arr[1]),
      message: dco_decode_String(arr[2]),
      tasksUpdated: dco_decode_usize(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  TaskRecord dco_decode_box_autoadd_task_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_task_record(raw);
  }

  @protected
  int dco_decode_i_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  LanPeerInfo dco_decode_lan_peer_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LanPeerInfo(
      deviceId: dco_decode_String(arr[0]),
      address: dco_decode_String(arr[1]),
      port: dco_decode_u_16(arr[2]),
    );
  }

  @protected
  LanSyncReport dco_decode_lan_sync_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LanSyncReport(
      peerId: dco_decode_String(arr[0]),
      success: dco_decode_bool(arr[1]),
      tasksUpdated: dco_decode_usize(arr[2]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BlePeer> dco_decode_list_ble_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ble_peer).toList();
  }

  @protected
  List<BlePeerIdentity> dco_decode_list_ble_peer_identity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ble_peer_identity).toList();
  }

  @protected
  List<LanPeerInfo> dco_decode_list_lan_peer_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_lan_peer_info).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TaskRecord> dco_decode_list_task_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_task_record).toList();
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_16(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  RelaySyncReport dco_decode_relay_sync_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RelaySyncReport(
      peerId: dco_decode_String(arr[0]),
      success: dco_decode_bool(arr[1]),
      tasksUpdated: dco_decode_usize(arr[2]),
    );
  }

  @protected
  TaskRecord dco_decode_task_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return TaskRecord(
      id: dco_decode_String(arr[0]),
      projectId: dco_decode_String(arr[1]),
      title: dco_decode_String(arr[2]),
      notes: dco_decode_String(arr[3]),
      dueMillis: dco_decode_opt_box_autoadd_i_64(arr[4]),
      tags: dco_decode_list_String(arr[5]),
      status: dco_decode_String(arr[6]),
      priority: dco_decode_i_64(arr[7]),
      createdAtMillis: dco_decode_i_64(arr[8]),
      updatedAtMillis: dco_decode_i_64(arr[9]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  WifiDirectSyncReport dco_decode_wifi_direct_sync_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WifiDirectSyncReport(
      peerId: dco_decode_String(arr[0]),
      success: dco_decode_bool(arr[1]),
      message: dco_decode_String(arr[2]),
      tasksUpdated: dco_decode_usize(arr[3]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BlePeer sse_decode_ble_peer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_address = sse_decode_String(deserializer);
    var var_rssi = sse_decode_opt_box_autoadd_i_16(deserializer);
    return BlePeer(
      deviceId: var_deviceId,
      displayName: var_displayName,
      address: var_address,
      rssi: var_rssi,
    );
  }

  @protected
  BlePeerIdentity sse_decode_ble_peer_identity(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_trusted = sse_decode_bool(deserializer);
    var var_lastSyncedAt = sse_decode_u_64(deserializer);
    return BlePeerIdentity(
      deviceId: var_deviceId,
      displayName: var_displayName,
      trusted: var_trusted,
      lastSyncedAt: var_lastSyncedAt,
    );
  }

  @protected
  BleSyncReport sse_decode_ble_sync_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_String(deserializer);
    var var_success = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_tasksUpdated = sse_decode_usize(deserializer);
    return BleSyncReport(
      peerId: var_peerId,
      success: var_success,
      message: var_message,
      tasksUpdated: var_tasksUpdated,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_16(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  TaskRecord sse_decode_box_autoadd_task_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_task_record(deserializer));
  }

  @protected
  int sse_decode_i_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt16();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  LanPeerInfo sse_decode_lan_peer_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_address = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    return LanPeerInfo(
      deviceId: var_deviceId,
      address: var_address,
      port: var_port,
    );
  }

  @protected
  LanSyncReport sse_decode_lan_sync_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_String(deserializer);
    var var_success = sse_decode_bool(deserializer);
    var var_tasksUpdated = sse_decode_usize(deserializer);
    return LanSyncReport(
      peerId: var_peerId,
      success: var_success,
      tasksUpdated: var_tasksUpdated,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BlePeer> sse_decode_list_ble_peer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BlePeer>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ble_peer(deserializer));
    }
    return ans_;
  }

  @protected
  List<BlePeerIdentity> sse_decode_list_ble_peer_identity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BlePeerIdentity>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ble_peer_identity(deserializer));
    }
    return ans_;
  }

  @protected
  List<LanPeerInfo> sse_decode_list_lan_peer_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LanPeerInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_lan_peer_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TaskRecord> sse_decode_list_task_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TaskRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_task_record(deserializer));
    }
    return ans_;
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RelaySyncReport sse_decode_relay_sync_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_String(deserializer);
    var var_success = sse_decode_bool(deserializer);
    var var_tasksUpdated = sse_decode_usize(deserializer);
    return RelaySyncReport(
      peerId: var_peerId,
      success: var_success,
      tasksUpdated: var_tasksUpdated,
    );
  }

  @protected
  TaskRecord sse_decode_task_record(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_projectId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_notes = sse_decode_String(deserializer);
    var var_dueMillis = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_priority = sse_decode_i_64(deserializer);
    var var_createdAtMillis = sse_decode_i_64(deserializer);
    var var_updatedAtMillis = sse_decode_i_64(deserializer);
    return TaskRecord(
      id: var_id,
      projectId: var_projectId,
      title: var_title,
      notes: var_notes,
      dueMillis: var_dueMillis,
      tags: var_tags,
      status: var_status,
      priority: var_priority,
      createdAtMillis: var_createdAtMillis,
      updatedAtMillis: var_updatedAtMillis,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  WifiDirectSyncReport sse_decode_wifi_direct_sync_report(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_String(deserializer);
    var var_success = sse_decode_bool(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_tasksUpdated = sse_decode_usize(deserializer);
    return WifiDirectSyncReport(
      peerId: var_peerId,
      success: var_success,
      message: var_message,
      tasksUpdated: var_tasksUpdated,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_ble_peer(BlePeer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.address, serializer);
    sse_encode_opt_box_autoadd_i_16(self.rssi, serializer);
  }

  @protected
  void sse_encode_ble_peer_identity(
    BlePeerIdentity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_bool(self.trusted, serializer);
    sse_encode_u_64(self.lastSyncedAt, serializer);
  }

  @protected
  void sse_encode_ble_sync_report(
    BleSyncReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peerId, serializer);
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_usize(self.tasksUpdated, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_16(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_task_record(
    TaskRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_task_record(self, serializer);
  }

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt16(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_lan_peer_info(LanPeerInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.address, serializer);
    sse_encode_u_16(self.port, serializer);
  }

  @protected
  void sse_encode_lan_sync_report(
    LanSyncReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peerId, serializer);
    sse_encode_bool(self.success, serializer);
    sse_encode_usize(self.tasksUpdated, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ble_peer(List<BlePeer> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ble_peer(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ble_peer_identity(
    List<BlePeerIdentity> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ble_peer_identity(item, serializer);
    }
  }

  @protected
  void sse_encode_list_lan_peer_info(
    List<LanPeerInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_lan_peer_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_task_record(
    List<TaskRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_task_record(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_16(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_relay_sync_report(
    RelaySyncReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peerId, serializer);
    sse_encode_bool(self.success, serializer);
    sse_encode_usize(self.tasksUpdated, serializer);
  }

  @protected
  void sse_encode_task_record(TaskRecord self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.projectId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.notes, serializer);
    sse_encode_opt_box_autoadd_i_64(self.dueMillis, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_i_64(self.priority, serializer);
    sse_encode_i_64(self.createdAtMillis, serializer);
    sse_encode_i_64(self.updatedAtMillis, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_wifi_direct_sync_report(
    WifiDirectSyncReport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.peerId, serializer);
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_usize(self.tasksUpdated, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
